version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jnupponen-scraper-python"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5k409vo6rxbe"
s3_prefix = "jnupponen-scraper-python"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppBucketName=\"jnupponen-scraper-python\""
